### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Albert221** [Albert221/flutter-versions-table#1]
- [ ] Dart SDK version in a given Flutter version
- [x] Use local (CSV?) database to persist data to avoid fetching everything #2 
  - Will help avoid hitting GitHub's rate-limit
- [x] Fetch all versions, not just 10 most recent #2
- [ ] Clean up code
